"""add project detail and contact models

Revision ID: 438f36409994
Revises: 
Create Date: 2026-08-19 03:56:01.282353+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# 迁移版本号
revision: str = '438f36409994'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='项目名称'),
    sa.Column('code', sa.String(length=100), nullable=False, comment='项目编号'),
    sa.Column('client', sa.String(length=255), nullable=True, comment='委托方'),
    sa.Column('location', sa.String(length=255), nullable=True, comment='项目地点'),
    sa.Column('type', sa.String(length=100), nullable=True, comment='项目类型'),
    sa.Column('scale', sa.String(length=255), nullable=True, comment='建设规模'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='开工日期'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='竣工日期'),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=False, comment='项目状态'),
    sa.Column('description', sa.Text(), nullable=True, comment='项目描述'),
    sa.Column('phase', sa.String(length=100), nullable=True, comment='项目阶段'),
    sa.Column('longitude', sa.Float(), nullable=True, comment='经度'),
    sa.Column('latitude', sa.Float(), nullable=True, comment='纬度'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_code'), 'projects', ['code'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_table('contact_persons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='项目ID'),
    sa.Column('contact_type', sa.Enum('client', 'team', name='contacttype'), nullable=False, comment='联系单类型：client委方 / team小组'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='姓名'),
    sa.Column('role', sa.String(length=255), nullable=True, comment='职务/专业'),
    sa.Column('phone', sa.String(length=50), nullable=True, comment='电话'),
    sa.Column('remarks', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_persons_project_id'), 'contact_persons', ['project_id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='项目ID'),
    sa.Column('code', sa.String(length=100), nullable=False, comment='合同编号'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='合同名称'),
    sa.Column('contract_type', sa.Enum('main', 'supplement', name='contracttype'), nullable=False, comment='合同类型'),
    sa.Column('party_a', sa.String(length=255), nullable=True, comment='甲方'),
    sa.Column('party_b', sa.String(length=255), nullable=True, comment='乙方'),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='合同金额'),
    sa.Column('signed_date', sa.Date(), nullable=True, comment='签订日期'),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=False, comment='合同状态'),
    sa.Column('content_text', sa.Text(), nullable=True, comment='合同正文'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('parent_contract_id', sa.Integer(), nullable=True, comment='主合同ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_contract_id'], ['contracts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_code'), 'contracts', ['code'], unique=False)
    op.create_index(op.f('ix_contracts_project_id'), 'contracts', ['project_id'], unique=False)
    op.create_table('project_buildings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='项目ID'),
    sa.Column('code', sa.String(length=100), nullable=False, comment='单体编号'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='单体名称'),
    sa.Column('building_nature', sa.String(length=255), nullable=True, comment='建筑性质'),
    sa.Column('building_function', sa.String(length=255), nullable=True, comment='建筑功能'),
    sa.Column('floors_above', sa.Integer(), nullable=True, comment='地上层数'),
    sa.Column('floors_under', sa.Integer(), nullable=True, comment='地下层数'),
    sa.Column('height', sa.Numeric(precision=8, scale=2), nullable=True, comment='建筑高度(m)'),
    sa.Column('floor_area', sa.Numeric(precision=18, scale=2), nullable=True, comment='建筑面积(㎡)'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_buildings_project_id'), 'project_buildings', ['project_id'], unique=False)
    op.create_table('project_culturals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='项目ID'),
    sa.Column('cultural_symbols', sa.Text(), nullable=True, comment='文化符号'),
    sa.Column('regional_architecture', sa.Text(), nullable=True, comment='地域建筑符号'),
    sa.Column('urban_color_scheme', sa.Text(), nullable=True, comment='城市设计色彩属性'),
    sa.Column('local_customs', sa.Text(), nullable=True, comment='地域风俗'),
    sa.Column('historical_culture', sa.Text(), nullable=True, comment='地域历史文化'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_culturals_project_id'), 'project_culturals', ['project_id'], unique=True)
    op.create_table('project_extras',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='项目ID'),
    sa.Column('field_key', sa.String(length=100), nullable=False, comment='扩展字段键'),
    sa.Column('field_value', sa.Text(), nullable=True, comment='扩展字段值'),
    sa.Column('ai_source', sa.String(length=100), nullable=True, comment='AI来源'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_extras_project_id'), 'project_extras', ['project_id'], unique=False)
    op.create_table('project_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='项目ID'),
    sa.Column('land_use', sa.String(length=255), nullable=True, comment='场地属性/用地性质'),
    sa.Column('site_area', sa.Numeric(precision=18, scale=2), nullable=True, comment='场地面积(㎡)'),
    sa.Column('far_above', sa.Numeric(precision=8, scale=4), nullable=True, comment='地上容积率'),
    sa.Column('far_under', sa.Numeric(precision=8, scale=4), nullable=True, comment='地下容积率'),
    sa.Column('green_ratio', sa.Numeric(precision=5, scale=2), nullable=True, comment='绿地率(%)'),
    sa.Column('building_density', sa.Numeric(precision=5, scale=2), nullable=True, comment='建筑密度(%)'),
    sa.Column('height_limit', sa.Numeric(precision=8, scale=2), nullable=True, comment='限高(m)'),
    sa.Column('total_floor_area', sa.Numeric(precision=18, scale=2), nullable=True, comment='总建筑面积(㎡)'),
    sa.Column('above_floor_area', sa.Numeric(precision=18, scale=2), nullable=True, comment='地上建筑面积(㎡)'),
    sa.Column('under_floor_area', sa.Numeric(precision=18, scale=2), nullable=True, comment='地下建筑面积(㎡)'),
    sa.Column('parking_above', sa.Integer(), nullable=True, comment='地上停车位数'),
    sa.Column('parking_under', sa.Integer(), nullable=True, comment='地下停车位数'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_metrics_project_id'), 'project_metrics', ['project_id'], unique=True)
    op.create_table('project_physicals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='项目ID'),
    sa.Column('climate_zone', sa.String(length=255), nullable=True, comment='气候区'),
    sa.Column('prevailing_wind', sa.String(length=255), nullable=True, comment='主导风向'),
    sa.Column('solar_path', sa.Text(), nullable=True, comment='日照轨迹'),
    sa.Column('annual_precipitation', sa.Numeric(precision=8, scale=1), nullable=True, comment='年降水量(mm)'),
    sa.Column('groundwater_level', sa.Numeric(precision=8, scale=2), nullable=True, comment='地下水位(m)'),
    sa.Column('elevation', sa.Numeric(precision=8, scale=2), nullable=True, comment='海拔(m)'),
    sa.Column('avg_annual_temp', sa.Numeric(precision=5, scale=1), nullable=True, comment='年平均气温(℃)'),
    sa.Column('extreme_max_temp', sa.Numeric(precision=5, scale=1), nullable=True, comment='极端最高温(℃)'),
    sa.Column('extreme_min_temp', sa.Numeric(precision=5, scale=1), nullable=True, comment='极端最低温(℃)'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_physicals_project_id'), 'project_physicals', ['project_id'], unique=True)
    op.create_table('project_surroundings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='项目ID'),
    sa.Column('longitude', sa.Float(), nullable=True, comment='经度'),
    sa.Column('latitude', sa.Float(), nullable=True, comment='纬度'),
    sa.Column('within_200m', sa.Text(), nullable=True, comment='200m范围周边'),
    sa.Column('within_500m', sa.Text(), nullable=True, comment='500m范围周边'),
    sa.Column('within_2000m', sa.Text(), nullable=True, comment='2000m范围周边'),
    sa.Column('nearby_roads', sa.Text(), nullable=True, comment='临近道路'),
    sa.Column('natural_features', sa.Text(), nullable=True, comment='自然景观'),
    sa.Column('transit_info', sa.Text(), nullable=True, comment='交通便利信息'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_surroundings_project_id'), 'project_surroundings', ['project_id'], unique=True)
    op.create_table('contract_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False, comment='合同ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='节点名称'),
    sa.Column('ratio', sa.Numeric(precision=5, scale=2), nullable=True, comment='占合同金额比例(%)'),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='节点金额'),
    sa.Column('plan_date', sa.Date(), nullable=True, comment='计划收款日期'),
    sa.Column('actual_date', sa.Date(), nullable=True, comment='实际收款日期'),
    sa.Column('status', sa.String(length=50), server_default='planned', nullable=False, comment='节点状态'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_nodes_contract_id'), 'contract_nodes', ['contract_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_nodes_contract_id'), table_name='contract_nodes')
    op.drop_table('contract_nodes')
    op.drop_index(op.f('ix_project_surroundings_project_id'), table_name='project_surroundings')
    op.drop_table('project_surroundings')
    op.drop_index(op.f('ix_project_physicals_project_id'), table_name='project_physicals')
    op.drop_table('project_physicals')
    op.drop_index(op.f('ix_project_metrics_project_id'), table_name='project_metrics')
    op.drop_table('project_metrics')
    op.drop_index(op.f('ix_project_extras_project_id'), table_name='project_extras')
    op.drop_table('project_extras')
    op.drop_index(op.f('ix_project_culturals_project_id'), table_name='project_culturals')
    op.drop_table('project_culturals')
    op.drop_index(op.f('ix_project_buildings_project_id'), table_name='project_buildings')
    op.drop_table('project_buildings')
    op.drop_index(op.f('ix_contracts_project_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_code'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_contact_persons_project_id'), table_name='contact_persons')
    op.drop_table('contact_persons')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_code'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
